//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDConection.BDModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Userid { get; set; }
        public string FullName { get; set; }
        public string EnglishLevel { get; set; }
        public string KnowlEdge { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string UrlResume { get; set; }
        public bool isActive { get; set; }
        public int Roleid { get; set; }
        public string Email { get; set; }
        public string Salt { get; set; }
        public string Password { get; set; }
        public string UserLogin { get; set; }
    }
}
